<script type="text/javascript"
        src="https://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js">
</script>
<script type="text/javascript">
    jQuery.noConflict();
</script>
<script type="text/javascript"
        src="https://partner.getfinancing.com/libs/1.0/getfinancing.js">
</script>
<script type="text/javascript">
<?php
    require_once 'EmPayTech/GetFinancing.php';

    $paymentMethod = Mage::getSingleton('getfinancing/paymentMethod');

    /* if not configured correctly, don't add the counter */
    if ($paymentMethod->isAvailable()) {

        $getfinancing = new GetFinancing_Magento($paymentMethod);
?>
    GetFinancing.counter({
        stage: 'landing',
        dataspace: '<?php echo $getfinancing->getDataspace(); ?>',
        merchantID: '<?php echo $getfinancing->merch_id; ?>'
    });
</script>
<?php
    }
?>
