<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
</script>
<script type="text/javascript"
        src="https://cdn.getfinancing.com/libs/1.0/getfinancing.js">
</script>
<?php
  /* we restore the jQuery and friends symbol, but save a copy to use in
   * our own jquery-using code */
?>
<script type="text/javascript">
    var gfjQuery = jQuery.noConflict(true);
</script>

<link rel="stylesheet" type="text/css"
      href="https://partner.getfinancing.com/libs/1.0/colorbox/colorbox.css">
</link>
<script type="text/javascript"
        src="https://partner.getfinancing.com/libs/1.0/colorbox/jquery.colorbox-min.js">
</script>
<div>
    <h1>LOL me if you can</h1>
    <div id="hyper-simulator"></div>
</div>

<script type="text/javascript">
<?php
    /* ajax listener inspired by
     * http://store.fooman.co.nz/extensions/magento-extension-googleanalyticsplus.html
     */
    require_once 'EmPayTech/GetFinancing.php';

    $paymentMethod = Mage::getSingleton('getfinancing/paymentMethod');
    $getfinancing = new GetFinancing_Magento($paymentMethod);
?>


jQuery(document).gfSimulator({
    debug: true,
    token: "<?php echo $getfinancing->merchant_token ?>",
    price: 1024,
    containerSelector: "#hyper-simulator"
});

gfjQuery(document).ready(function() {
    if (Ajax.Responders) {
        Ajax.Responders.register({onComplete: function (response) {
            var oldjQuery = jQuery;
            jQuery = gfjQuery;

            // console.log('response url: ' + response.url);
            if (response.url.include('toStep=payment')) {
                console.log('GetFinancing: moved to payment step');

            // add getfinancing image and faq link
            // FIXME: when reaching this step, magento resets the contents of input
            var input = gfjQuery('#p_method_getfinancing');
            var dt = input.parent();
            gfjQuery(dt).append('<div id="getfinancing-faq-parent" ' +
                'style="display: inline-block; vertical-align: middle;" />');

            /* FIXME: calculate platformURL to lc/info/visits instead so
             *        we can use against other platforms than production */
            GetFinancingSimple.init({
                dataspace: '<?php echo $getfinancing->getDataspace(); ?>',
                merchantID: '<?php echo $getfinancing->merch_id; ?>'
            });

            console.log('add faq link');
            GetFinancingSimple.addFaqLink({
                src: 'media/1.0/buttons/png/btn_getfinancing_200x36_b.png',
                selector: '#getfinancing-faq-parent'
            });
            console.log('added faq link');

            GetFinancingSimple.counter('payment');


            }
            jQuery = oldjQuery;
        }});
    }
});
</script>
