The GetFinancing box will now open and take you through the financing
application process.
<script type="text/javascript"
        src="https://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js">
</script>
<script type="text/javascript"
        src="https://cdn.getfinancing.com/libs/1.0/getfinancing.js">
</script>
<?php
  /* we restore the jQuery and friends symbol, but save a copy to use in
   * our own jquery-using code */
?>
<script type="text/javascript">
    var gfjQuery = jQuery.noConflict(true);
</script>
<?php

    $session = Mage::getSingleton('checkout/session');
    $url = $session->getGetFinancingApplicationURL();
    if (! $url) {
        /* FIXME: use a test url so we can refresh this page */
        Mage::log('GetFinancing: checkout/session: no url in session, faking it');
        $url = "https://partner-test.getfinancing.com/partner-test/lc/info/5916db59362013d4391982a270ef87fa";
    }

    $paymentMethod = Mage::getSingleton('getfinancing/paymentMethod');
    $getfinancing = new GetFinancing_Magento($paymentMethod);
?>
<script type="text/javascript">

    /* we make sure all code from getfinancing.js has the expected jQuery */
    var oldjQuery = jQuery;
    jQuery = gfjQuery;

    GetFinancing.counter({
        stage: 'payment',
        dataspace: '<?php echo $getfinancing->getDataspace(); ?>',
        merchantID: '<?php echo $getfinancing->merch_id; ?>'
    });

    var url = '<?php echo $url; ?>';
    var onComplete = function() {
        // this is called when the user finishes all the steps and
        // gets loan preapproved
        gfjQuery('#getfinancing-message').text(
            'Loan preapproved.  Redirecting you to the success page.');

        var success = '<?php echo Mage::getUrl('getfinancing/standard/success'); ?>';
        window.location = success;
    };
    var onAbort = function() {
        // this is called when the user closes the lightbox before
        // finishing all the steps

<?php
/*
    $checkout_url = Mage::getUrl('checkout/onepage',
        array("_secure" => (
            isset($_SERVER["HTTPS"]) &&
            ($_SERVER["HTTPS"] === "on")
        ))
    );
      */

      $session = Mage::getSingleton('checkout/session');
      $quoteId = $session->getQuoteId();
      $quote = Mage::getModel("sales/quote")->load($quoteId);
      $quote->setIsActive(false)->save();
      $session->clear();
      Mage::log("GetFinancing: session quoteId ". $quoteId);

    $checkout_url = Mage::getUrl("getfinancing/standard/cancel",array('_query' => array("q" => $quoteId)));
?>
        gfjQuery('#getfinancing-message').html(
            'Payment aborted.  Redirecting you to the payment choice.<br/>' +
            'If this page does not refresh automatically, ' +
            '<A href="<?php echo $checkout_url; ?>">click here</A>.');
        var failure = '<?php echo $checkout_url; ?>';
<?php
    $version = Mage::getVersion();
    if (version_compare ($version, '1.5.0', '<')) {
?>
        // FIXME: if we redirect like this, we go to the start of the
        //        onpage checkout
        // FIXME: In 1.4.1.1, I get a TypeError on the console when doing
        //        checkout.gotoSection:
        //        TypeError: section.addClassName is not a function
        window.location = failure;
<?php
    } else {
?>
        // this one takes us back to the one page checkout and sets it to the
        // payment tab in the accordion
        gfjQuery('body').load(failure, {}, function () {
            // set the magento onepage checkout accordion to the payment section
            checkout.gotoSection('payment');
        });
<?php
    }
?>

    };
    new GetFinancing(url, onComplete, onAbort);
    jQuery = oldjQuery;
</script>
<h2 id="getfinancing-message"></h2>
