The GetFinancing box will now pop up and take you through the process of
getting a loan.
<script type="text/javascript"
        src="https://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js">
</script>
<script type="text/javascript">
    jQuery.noConflict();
</script>
<script type="text/javascript"
        src="https://partner.getfinancing.com/libs/1.0/getfinancing.js">
</script>
<?php

    $session = Mage::getSingleton('checkout/session');
    $url = $session->getGetFinancingApplicationURL();
    if (! $url) {
        /* FIXME: use a test url so we can refresh this page */
        Mage::log('THOMAS: No url in session, faking it');
        $url = "https://partner-test.getfinancing.com/partner-test/lc/info/5916db59362013d4391982a270ef87fa";
    }

    $paymentMethod = Mage::getSingleton('getfinancing/paymentMethod');
    $getfinancing = new GetFinancing_Magento($paymentMethod);
?>
<script type="text/javascript">

    GetFinancing.counter({
        stage: 'payment',
        dataspace: '<?php echo $getfinancing->getDataspace(); ?>',
        merchantID: '<?php echo $getfinancing->merch_id; ?>'
    });

    var url = '<?php echo $url; ?>';
    var onComplete = function() {
        // this is called when the user finishes all the steps and
        // gets loan preapproved
        jQuery('#getfinancing-message').text(
            'Loan preapproved.  Redirecting you to the success page.');

        var success = '<?php echo Mage::getUrl('getfinancing/standard/success'); ?>';
        window.location = success;
    };
    var onAbort = function() {
        // this is called when the user closes the lightbox before
        // finishing all the steps

        jQuery('#getfinancing-message').text(
            'Payment aborted.  Redirecting you to the payment choice.');
        var failure = '<?php echo Mage::getUrl('checkout/onepage'); ?>';
<?php
    $version = Mage::getVersion();
    if (version_compare ($version, '1.5.0', '<')) {
?>
        // FIXME: if we redirect like this, we go to the start of the
        //        onpage checkout
        // FIXME: In 1.4.1.1, I get a TypeError on the console when doing
        //        checkout.gotoSection:
        //        TypeError: section.addClassName is not a function
        window.location = failure;
<?php
    } else {
?>
        // this one takes us back to the one page checkout and sets it to the
        // payment tab in the accordion
        jQuery('body').load(failure, {}, function () {
            // set the magento onepage checkout accordion to the payment section
            checkout.gotoSection('payment');
        });
<?php
    }
?>

    };
    new GetFinancing(url, onComplete, onAbort);
</script>
<h2 id="getfinancing-message"></h2>
