<script type="text/javascript"
        src="https://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js">
</script>
<script type="text/javascript">
    jQuery.noConflict();
</script>
<script type="text/javascript"
        src="https://partner.credex.net/libs/1.0/credex.js">
</script>
<link rel="stylesheet" type="text/css"
      href="https://partner.credex.net/libs/1.0/colorbox/colorbox.css">
</script>
<script type="text/javascript"
        src="https://partner.credex.net/libs/1.0/colorbox/jquery.colorbox-min.js">
</script>

<script type="text/javascript">
<?php
    /* ajax listener inspired by
     * http://store.fooman.co.nz/extensions/magento-extension-googleanalyticsplus.html
     */
    require_once 'EmPayTech/CredEx.php';

    $paymentMethod = Mage::getSingleton('credex/paymentMethod');
    $credex = new CredEx_Magento($paymentMethod);
?>

jQuery(document).ready(function() {
    if (Ajax.Responders) {
        Ajax.Responders.register({onComplete: function (response) {
            // console.log('response url: ' + response.url);
            if (response.url.include('toStep=payment')) {
                console.log('Credex: moved to payment step');

            // add credex image and faq link
            // FIXME: when reaching this step, magento resets the contents of input
            var input = jQuery('#p_method_credex');
            var dt = input.parent();
            jQuery(dt).append('<div id="credex-faq-parent" ' .
                'style="display: inline-block; vertical-align: middle;" />');

            /* FIXME: calculate platformURL to lc/info/visits instead so
             *        we can use against other platforms than production */
            CredexSimple.init({
                dataspace: '<?php echo $credex->getDataspace(); ?>',
                merchantID: '<?php echo $credex->merch_id; ?>'
            });

            console.log('add faq link');
            CredexSimple.addFaqLink({
                src: 'media/1.0/buttons/png/btn_credex_200x36.png',
                selector: '#credex-faq-parent'
            });
            console.log('added faq link');

            CredexSimple.counter('payment');


            }
        }});
    }
});
</script>
