The Credex box will now pop up and take you through the process of
getting a loan.
<script type="text/javascript"
        src="https://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js">
</script>
<script type="text/javascript">
    jQuery.noConflict();
</script>
<script type="text/javascript"
        src="https://partner.credex.net/libs/1.0/credex.js">
</script>
<?php

    $session = Mage::getSingleton('checkout/session');
    $url = $session->getCredexApplicationURL();
    if (! $url) {
        /* FIXME: use a test url so we can refresh this page */
        Mage::log('THOMAS: No url in session, faking it');
        $url = "https://partner-test.credex.net/partner-test/lc/info/5916db59362013d4391982a270ef87fa";
    }

    $paymentMethod = Mage::getSingleton('credex/paymentMethod');
    $credex = new CredEx_Magento($paymentMethod);
?>
<script type="text/javascript">

    Credex.counter({
        stage: 'payment',
        dataspace: '<?php echo $credex->getDataspace(); ?>',
        merchantID: '<?php echo $credex->merch_id; ?>'
    });

    var url = '<?php echo $url; ?>';
    var onComplete = function() {
        // this is called when the user finishes all the steps and
        // gets loan preapproved
        jQuery('#credex-message').text(
            'Loan preapproved.  Redirecting you to the success page.');

        var success = '<?php echo Mage::getUrl('credex/standard/success'); ?>';
        window.location = success;
    };
    var onAbort = function() {
        // this is called when the user closes the lightbox before
        // finishing all the steps

        jQuery('#credex-message').text(
            'Payment aborted.  Redirecting you to the payment choice.');
        var failure = '<?php echo Mage::getUrl('checkout/onepage'); ?>';
        // FIXME: if we redirect like this, we go to the start of the
        //        onpage checkout
        //window.location = failure;

        // this one takes us back to the one page checkout and sets it to the
        // payment tab in the accordion
        jQuery('body').load(failure, {}, function () {
            // set the magento onepage checkout accordion to the payment section
            checkout.gotoSection('payment');
        });

    };
    new Credex(url, onComplete, onAbort);
</script>
<h2 id="credex-message"></h2>
